title: martabyte
description: red team operator · ctf · ios · learning
url: "https://martabyte.github.io"
baseurl: ""

author:
  alias: afr0dita
  focus: web exploitation · ad · ios
  deployed_at: blackarrow
  pgp: 0xDEADBEEF
  pgp_fingerprint: "DEAD BEEF 1337 C0DE CAFE BABE F00D D00D 0000 0001"
  coffee: CRITICAL
  soundtrack: L7 · Bikini Kill · Led Zeppelin
  htb_rank: HACKER
  htb_pwned: 24
  htb_challenges: 12
  htb_ubloods: 0
  htb_rbloods: 0
  htb_points: x
  htb_top: x
  htb_best: web · forensics
  htb_since: "2018-04-14"
  certs:
    - badge: OSCP+
      name: Offensive Security Certified Professional+
      issuer: Offensive Security
      year: 2025
      wip: false
    - badge: CRTP
      name: Certified Red Team Professional
      issuer: Pentester Academy
      year: 2021
      wip: false
    - badge: CEH (Master)
      name: Certified Ethical Hacker (Master)
      issuer: EC-Council
      year: 2021
      wip: true
  contact:
    - key: github
      val: github.com/martabyte
      url: https://github.com/martabyte
    - key: twitter/x
      val: "@martabyte"
      url: https://twitter.com/martabyte
    - key: htb
      val: app.hackthebox.com/profile/aphr0dite
      url: https://app.hackthebox.com/profile/aphr0dite
    - key: email
      val: afr0dita [at] proton [dot] me
      url: mailto:afr0dita@proton.me

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /posts/:slug/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
